reem/rust-ordered-float

Cargo.toml

We only need the Float trait, so dropping default features cuts a lot
out of num we don't want, including the rustc_serialize dependency

Disable default features for num

---

src/lib.rs
tests/test.rs

I've added `ops` implementations for _addition_, _subtraction_, _multiplication_, _division_, _modulo_ and _negation_ to NotNaN.
This makes it easier to work with the types as it is often tedious to always `deref -> calc -> unsafe new` within your program.
I started the discussion for this in #11 some months ago and got at least one positive feedback.

Added `ops` for calculation to `NotNaN`

---

src/lib.rs
tests/test.rs

This fixes #18 by introducing a better implementation of `Hash` which improves the added tests such that neither has any collisions. Previously, the whole number test had `~50%` unique hash codes, and the fractional test had `~80%` unique hash codes.
Also, my  `auto-rustfmt` kicked in on a few lines, hence the unrelated whitespace changes.

Fix skew in hash computation

---

src/lib.rs

Add additional checks to remove possibility of NotNaN containing NaN

---

src/lib.rs
tests/test.rs
tests/test_deprecated_names.rs

[Rust's RFC 0430 about naming conventions](https://github.com/rust-lang/rfcs/blob/master/text/0430-finalizing-naming-conventions.md#fine-points) says:
> In `CamelCase`, acronyms count as one word: use `Uuid` rather than `UUID`.
Standard library follows this rule and uses `Nan` (see [`std::num::FpCategory::Nan`](https://doc.rust-lang.org/std/num/enum.FpCategory.html#variant.Nan)), so this crate had better use `Nan`.

Prefer `Nan` to `NaN`

---

.travis.yml
src/lib.rs

Make structs repr(transparent)

---

Cargo.toml
src/lib.rs

Replace it with `std::hint::unreachable_unchecked` which is stable in Rust 1.27.

Remove unreachable dependency

---

src/lib.rs

Various small code updates & refactors, focused on removing redundant asserts and deduplication.
Fixes #54

Various small updates

---

Cargo.toml
src/lib.rs
tests/test.rs
tests/test_deprecated_names.rs

This crate was not actually no_std compatible because it (1) used
num-traits with the `std` feature, and (2) relied on the `Float` trait,
which is unavailable in no_std.
I have altered it to rely on `FloatCore` instead and passed the feature
flag through to the dependency.
Had to bump the version of num-traits required, because FloatCore only
appeared in 0.2.1.

In no_std context, use no_std num-traits.

---

src/lib.rs
tests/test.rs

These are straightforward, just like Add/Mul

Add Sum/Product impls for NotNan

---

src/lib.rs

Useful for the pathfinding crate

Add Zero impl for OrderedFloat

---

src/lib.rs
tests/test.rs

This solves #67 by changing `NotNan::unchecked_new()` to use `const fn`, allowing its usage in const contexts.
The only real API change, other than the `const fn`, is that the structural bound for `NotNan<T>` is no longer limited to `T: Float`. However, all of the `impl` blocks for `NotNan<T>` still require `T: Float`. This should allow the `const fn` while also minimizing the change in behavior.
I also removed the `debug_assert!()` statement from the function, since allowing `if` statements in a const context would force the MSRV to bump up by quite a few versions. If this is acceptable I will add it back.

Change unchecked_new to use const fn

---

src/lib.rs
tests/test.rs

Current behavior allows UB in safe code.

Make assignment operators panic safe

---

.github/workflows/tests.yaml
Cargo.toml
src/lib.rs

Hello @mbrubeck , @reem et al, thanks for this useful library.  Here's a feature enhancement that could help out.
I would like to use types from `ordered-float` in one of my JSON APIs.  The JSON API has a constraint that all involved types must implement `JsonSchema` from the [schemars](https://github.com/GREsau/schemars/) crate in order to wire up autogeneration of JSON schema for API documentation and discoverability.
`schemars` is added as an optional dependency. Implementations of `JsonSchema` for `OrderedFloat<f32|f64>` and `NotNan<f32|f64>` are provided behind feature flag gating. Both "std" and "schemars" features are required, as the `schemars` crate is firmly `std`-only.
The provided schema match the pre-existing `serde` implementations which serialize the underlying float value …

Add optional JsonSchema support

---

.github/workflows/tests.yaml
Cargo.toml
src/lib.rs

Related issue: #83. Implements sampling in the Standard, Open01, and OpenClosed01 distributions. Uniform sampling is also implemented.
This is my first Rust PR and I wouldn't mind feedback.

Implement traits from the 'rand' crate.

---

src/lib.rs

This follows the naming convention of the Rust standard libraries.
Issue: #85

Add 'new_unchecked' and mark 'unchecked_new' as deprecated.

---

rustfmt.toml
src/lib.rs
tests/test.rs

I've formatted the code with the default settings. It looks fine to me but it is a bit more verbose / less terse than before. We might want to use the `fn_single_line` and `where_single_line` options for rustfmt but they haven't been stabilized yet. I've written a note about this in `rustfmt.toml`.

Use rustfmt to apply standard and consistent formatting.

---

Cargo.toml
src/lib.rs

`proptest` doesn't support `no_std` on stable. Will this cause trouble or is it fine as long as the dependency is optional?

Implement Arbitrary instances from proptest.

---

.github/workflows/tests.yaml

The latest `proptest` crate requires a more recent Rust version.  This also protects against similar breakage in other optional dependencies.

Don't test optional features on Rust 1.36

---

Cargo.toml
src/lib.rs

Similar to serde support this adds optional support for the [`rkyv`](https://github.com/rkyv/rkyv) (de)serialization framework for `OrderedFloat` and `NotNan`. It is feature-gated the same way serde is.
Implementations are based on the trait implementations for primitives from the `rkyv` crate instead of derive macros to avoid the intermediate `ArchivedX` type that doesn't implement the comparison traits.

Add optional support for rkyv

---

src/lib.rs

`unsafe { mem::transmute::<i16, u16>(exp) } as u64` is equivalent to `exp as u16 as u64`, this can be verified with a simple program:
```rust
fn main() {
for i in i16::MIN ..= i16::MAX {
assert_eq!(
unsafe { std::mem::transmute::<i16, u16>(i) } as u64,
i as u16 as u64
)
}
}
```

Replace unsafe transmute to a cast

---

src/lib.rs

This fixes #102. Should I bump the minor version, too?

Add `From<i32>` and similar impls to `NotNan`

---

Cargo.toml
src/lib.rs
tests/test.rs

Adds an implementation of [`arbitrary::Arbitrary`](https://crates.io/crates/arbitrary) for both `OrderedFloat` and `NotNan`. This allows code that uses `ordered-float` to be more easily tested using [`cargo fuzz`](https://github.com/rust-fuzz/cargo-fuzz).
I've been successfully using this algorithm as an explicit function in my own project; adding it as a trait implementation for the type will make it possible to just use `#[derive(Arbitrary)]` on types containing `NotNan` or `OrderedFloat`.

`impl arbitrary::Arbitrary` for `NotNan` and `OrderedFloat`.

---

.github/workflows/tests.yaml
Cargo.toml
src/lib.rs
tests/test.rs

This PR adds checks for rustfmt and clippy to the workflow.
The dangling v2.10.0 tag has been merged into master, thereby setting the version in Cargo.toml to 2.10.0. The version fo the `schemars` dependency has also been bumped up to version 0.8.8, the latest version.
1 needless borrow has been removed and another one was allowed and annotated since the msrv 1.36.0 required it.

Adds clippy and rustfmt to workflow + small cleanups

---

src/lib.rs

Currently, it's not cleanly possible to convert a `NotNan<f64>` to a `NotNan<f32>` if you're aware of the precision loss and are ready to take it without unwrapping and re-wrapping again.
So this PR addresses this through adding a `NotNan::<f64>::into_notnan_f64_lossy` which does that automatically.
I'm not sure about the naming of the method. I'd like to shorten it, and also I'm not sure whether that's a case for using `as_` naming, as the Rust API guidelines suggest.

Add lossy conversion for `NotNan<f64>` to `NotNan<f32>`

---

src/lib.rs

I just ran into a case where I wanted to format `OrderedFloat`s in scientific notation using `std::fmt::LowerExp` and `std::fmt::UpperExp`. This adds delegate implementations for both of those traits.
```rust
use ordered_float::OrderedFloat;
fn main() {
let n = OrderedFloat(10.2);
println!("{:+.2e}", n); // prints "+1.02e1"
}
```

Add scientific notation `Display` impls

---

Cargo.toml
README.md
src/lib.rs

This adds an implementation of [`speedy`](https://github.com/koute/speedy)'s `Readable` and `Writable` traits for `OrderedFloat` and `NotNan`.

Add speedy serialization feature

---

Cargo.toml
src/lib.rs

I know that there is already a previous PR (#108) for adding this support for bytemuck. However it seems that it is stuck without any updates for a long time. I tried to fix the code from that PR only implementing `bytemuck::NoUninit` and `bytemuck::CheckedBitPattern` for `NotNan`.
If there is anything that could still be improved in the PR please let me know.

Add support for bytemuck

---

.github/workflows/tests.yaml
Cargo.toml
src/lib.rs

This will support `rkyv` with different size types.

Split `rkyv` feature by `size_xx`.

---

Cargo.toml
src/lib.rs

Derive traits for `rand` types

---

Cargo.toml
src/lib.rs

Sorry, I forgot to actually test `cargo check --features rkyv_64`. It does not work because `rkyv_64 = ["dep:rkyv", "rkyv/size_64"]` treats `rkyv` in  `"rkyv/size_64"` as feature instead of dependency and `"dep:rkyv/size_64"` is invalid. The fix is to avoid namespaced features when we have to enable a dependency of a dependency. I've tried `rkyv_64 = ["dep:rkyv", "rkyv?/size_64"]` as well and it first seems to work but as soon as `ordered-float` is used in another crate it breaks.

Fix split of `rkyv` feature.

---

src/lib.rs
tests/test.rs

Hi!
I noticed that for hashing ordered floats, we normalize NaN to a unique representation, just to later check for .is_nan() in raw_double_bits anyway.
Also, for NotNan, we have this .is_nan() check in raw_double_bits, even though it can never be true due to the NotNan invariant.
So I decided to try to restructure the hashing code a bit. The special cases are now all handled uniformly inside the hash implementations, and raw_double_bits just does the raw bit conversion, without any special handling.
I took care to not change the actual resulting hashes, in case that's relevant for backwards compatibility.
Also, I added a test case for mapping 0 and -0 for NotNan to the same hash, and one for mapping different representations of NaN for OrderedFloat to the same hash.

Refactor hash float

---

src/lib.rs
tests/test.rs

Issue #118 asked for implementation of the Pow trait for OrderedFloat and NotNan. I have implemented the Pow trait for both in 2 ways. 
1. This implements the trait for exponents that are primitive types (i8, i16, i32, u8, u16, f32, f64) that num_traits does, https://docs.rs/num-traits/latest/num_traits/pow/trait.Pow.html, for the f32 and f64 types respectfully. 
2. This implements the trait for exponents and bases that both either OrderedFloat or NotNan. 
I have not implemented any mixing of OrderedFloat and NotNan, as the proper return type is not obvious. I have also not implemented Pow for the base being primitive (i8, i16, i32, u8, u16, f32, f64) with an exponent of either OrderedFloat or NotNan, as again the return type for this operation is not clear to me.
I also added a few tests …

Pow support

---

src/lib.rs

I'd like to be able to access `UniformOrdered` from the `impl_rand` module. I'm not sure why the struct is not exposed by default, but this PR allows for that. 
I can imagine why the `impl_rand` module is not public, but I wonder what the proper way would be for this crate to expose `UniformOrdered`.
Any pointer are appreciated

Make `impl_rand` public

---

src/lib.rs

The standard `f64` and `f32` types support conversion from integer types for which the conversion will not lose precision, as well as from `bool`. This commit adds that same support to `OrderedFloat`.

Support the same conversions from integer types as `f64` and `f32`.

---

src/lib.rs
tests/test.rs

I've notice, that you are using `NotNan<T>`/`OrderedFloat<T>` as Archived values. This leads to compilation failure if rkyv used with `archive_le` or `archive_be` features:
```
cargo t -F rkyv/archive_le
```
```
error[E0308]: mismatched types
--> src/lib.rs:2013:46
|
2013 |         let deser_float: OrderedFloat<f64> = archived_value.deserialize(&mut deserializer).unwrap();
|                          -----------------   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `OrderedFloat<f64>`, found `With<_, _>`
|                          |
|                          expected due to this
|
= note: expected struct `OrderedFloat<f64>`
found struct `With<_, _>`
```
My PR implements `rkyv::Archive` properly considering this features

Implement `rkyv` endianess

---

src/lib.rs
tests/test.rs

Previously, the `std` feature was non-additive; that is, it was possible for *enabling* the `std` feature to break code in another crate. Specifically, consider the following code:
```rust
fn problem<T>(inputs: &mut [OrderedFloat<T>])
where
T: num_traits::float::FloatCore,
{
inputs.sort();
}
```
This code will compile if the `std` feature is disabled, but then fail when it is enabled because `Ord for OrderedFloat<T>` requires that `T: Float`, rather than `T: FloatCore`.
In order to eliminate this compatibility hazard, instead always require `FloatCore` and, where necessary, also require `Float`.
**This is a breaking change;** generic code may need updated bounds.
Also, for reasons I do not entirely understand, `#[derive(PartialEq)]` wouldn't compile for the `UniformNotNan` and …

Unconditionally bound with `T: FloatCore`.

---

src/lib.rs
tests/test.rs

These micro-optimizations significantly reduce the number of instructions comparisons take, and often makes them branchless as well. Similarly we use a trick to canonicalize signed zero to positive zero in a single instruction without branches for faster hashing.

Optimize ord implementation and signed zero canonicalization

---

src/lib.rs
tests/test.rs

Ill-behaved FloatCore implementations for user types could have `x.partial_cmp(&x) == None` even when `x.is_nan() == false`.  This crate will now panic in those cases, rather than execute undefined behavior.
Fixes #150.

Fix soundness bug in NotNan::partial_cmp.

---

src/lib.rs

Make `Debug` impls delegate directly to inner float

---

Cargo.lock
Cargo.toml
src/lib.rs

feat: optionally integrate with num-cmp

---

src/lib.rs

Currently, rustdoc only displays `repr(transparent)` if the type’s fields are public, so there is no indication in the documentation that `NotNan` has `repr(transparent)`. Even if it was visible, there is not currently a strong consensus that such a repr may be assumed to be a stable part of the public API.
Therefore, I propose to add paragraphs to `NotNan` and `OrderedFloat`’s documentation guaranteeing the repr. I also mentioned `bytemuck` so as to not be encouraging unsafe code, though the phrasing isn’t great.
I’ve also added `impl bytemuck::TransparentWrapper for OrderedFloat`, which simply gives another way for users to perform conversions, more strongly typed than `bytemuck`’s casts to/from bytes.

Document that `NotNan` is `repr(transparent)`.

---

src/lib.rs

Fixes #157.
Also remove a stray blank line that showed up in the documentation.

Document signed zero hazards.

---

.github/workflows/tests.yaml

This should fix all deprecation warnings currently issued by GitHub Actions.
actions-rs/toolchain and actions-rs/cargo are both unmaintained, but they can largely be replaced with plain `rustup` and `cargo` commands, except for the problem matchers.

CI: update actions/checkout, remove actions-rs/*

---

Cargo.lock
Cargo.toml
src/lib.rs

@mbrubeck For my use case and it seems a good add-on.

feat: integrate with derive-visitor

---

src/lib.rs
tests/test.rs

Given [the problems](https://github.com/reem/rust-ordered-float/issues/91) with a pure delegated impl, add a Copy bound and LLVM will probably optimize it away anyways.

feat: [resolves #145] &OrderedFloat <op> &OrderedFloat impl workaround

---

src/lib.rs
tests/test.rs

Resolves #166 as discussed there.
Tests that disappear are those that relate to `not_nan += maybe_nan` panicking which now doesn't compile.
Apologies for the small amount of extra auto-formatting, please let me know if that is an issue and I'll remove it.

Remove implicit panics in NotNan<T> x T operators

---

src/lib.rs

The previous generic implementation was slow, and potentially incorrect for custom types.  Fixes #142.

Implement Hash for f32 and f64 only.

---

src/lib.rs
tests/test.rs

This is the counterpart of the implementation of Float for OrderedFloat as Real is "[A trait for real number types that do not necessarily have floating-point-specific characteristics such as NaN and infinity](https://docs.rs/num-traits/latest/num_traits/real/trait.Real.html)."
Operations that would result in a NaN cause a panic, as it is the behaviour that it suggested in the num_trait docs. Checks for NaN results are only done in cases where a NaN could be expected, and assumes that the implementation of Real for the underlying type is sane otherwise.

Implements num_traits::real::Real for NotNan<T>
